### ISSUE TITLE
CLI - implement searching of usernames in database

### ISSUE THREAD

**Issue by tomeon** [BaxterStockman/cloudendar#9]
Once the database is complete, we should be able to pull and display username data as the user searches for usernames in the search form. This should be accomplished with the Whoose text search module.

Once search results are displayed, users should be able to add the usernames of interest to the list that will be used to generate free/busy time slots.

**Comment by clampitc** [comment]
You mention one the DB is complete? Do we need something added to it? A new
table or field? If so let me know. I still have no idea how to use Alchemy
so I would simply do this old school as it makes is easy and quick. Can you
pull anything form the DB right now?

Charles

**Comment by tomeon** [comment]
Hi Charles,

I see no commits from you for the past several weeks in our GitHub repo, 
so if the database is finished it's news to me.  The thing with 
SQLAlchemy is that both Kayla and I are looking for a convenient 
interface for accessing the database from within our applications, and 
SQLAlchemy provides that.  A related advantage is that it really eases 
the development of the database's models, as you can see if you check 
out models.py in the src directory. Having to do everything manually 
using Python's SQLite3 module is just going to be a pain, so please take 
the time to look over models.py and gain an understanding of 
SQLAlchemy.  There's copious and straightforwards documentation on the 
web as well.

Thanks,

Matt

**Comment by clampitc** [comment]
Does Kalya know how to use this because last I talked to her she had no
clue as well. If you want to use Alchemy please setup a time with me and
demo what I should do so that I am not spending an entire weekend to learn
something that you know and I can get a demo in 10 minutes and be up and
going. as for the Db I had to give Kayla a copy directly so that she can
use it. So why don't we figure out when you and I can get together later
tonight or early morning tomorrow and I can take the DB we have been
working with and see how I am to use this with some tool that I do not know
how to use yet.

Laurye and I were just heading out the door for 3 hours to go shop for our
son that leaves for UNC Chapel hill in a few weeks (full ride in honors and
chancellors program) and we have to get him stuff this weekend before he
leaves. It is 2:45PM here but if you can shoot for 6:30PM here I can be
sure to be here and set up and we can go over what you need and how we
should use this new tool. Do I need to install anything? If so please send
me a link to where to install would be for a Win7. If you would prefer to
do this Sunday morning then this is fine as well. I have overloaded this
weekend so I need to make short quick strides towards our goals.

Hope the tone is not coming across too harsh. Don't mean it to be just
don't have time this next few weeks to monkey with something that I am not
familiar with if it complicates everything. Is Kayla using
the interface yet? Does she know how to use it. If not maybe we should get
her in and help her configure this as well so she does not spend extra
cycle figuring out something you already know and can transfer that
knowledge quickly.

If you are available right now (I will wait 15 minutes after sending this
email) and can have a call to take me through the setup then great. If not
then in 3 1/2 hours from now or tomorrow morning would be fine as well.
Text me when you are ready  or if you can at a certain time so that I can
get this done as soon as possible.

503-970-0188 cell

Charles

**Comment by clampitc** [comment]
I sent a few texts and am still waiting for a reply to see if you can get
15 minutes to show the demo of this app that you want us to use and show me
that it is configured and working so we can create a single DB. I need to
see that we can create a single DB, see where it is at, and how to add data
to it such as if I am writing python scripts can I use Alchemy to add data
to this DB?

Also, I though it was a requirement that we be able to run everything on
the engineering servers? Have you tested that Alchemy works there? Can we
install it there? I know SQL Lite works there because I tested it.

Also, is Kayla up on this tool and she knows how to use it, how to connect
to it, and her CLI code will work with it? Let me know when we can do a
walkthrough?

Charles

**Comment by tomeon** [comment]
Charles,

If you don't want to use SQLAlchemy, that is fine -- just please realize 
that there is no way around learning another tool: either we learn how 
to use the convenient, abstracted interface of SQLAlchemy, or we learn 
how to use the SQLite3 module.  I am not going to provide a tutorial on 
SQLAlchemy; everything I know about it I learned through 
easily-accessible documentation and tutorials, the same way that I have 
learned how to use every single other one of the many tools that I've 
used in the project so far.  You can feel free to research these if you 
are interested in doing so; otherwise, please continue to use straight 
SQLite3, and inform Kayla and me about how to access the database. This 
website 
http://www.pythoncentral.io/introductory-tutorial-python-sqlalchemy/ 
might be a good place to start if you want to learn about SQLAlchemy.  
I'll also mention again that the file models.py in the source directory 
contains definitions of SQLAlchemy models that should be appropriate for 
the sort of data that we need to deal with, it just needs a little bit 
of tweaking to make sure that it properly tracks the current state of 
our conceptual schema.

As for the requirement that everything run on the engineering servers -- 
McGrath has stated that we don't actually need to run the application on 
the engineering servers, it just has to be /possible/, given the proper 
permissions, to install all necessary modules, do the necessary 
configuration, and so on.  As long as we properly document the 
requirements and the setup process, we are golden.

Matt
